// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvZGWqnvbHQ7afw0pwyHn7a3hs6iBz0s',
    appId: '1:188263250841:web:58462b4a0a98fcd7557108',
    messagingSenderId: '188263250841',
    projectId: 'app1-1015b',
    authDomain: 'app1-1015b.firebaseapp.com',
    storageBucket: 'app1-1015b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhxUZd3Wih0S2QEHSGtOHjQI0RuoIjNg',
    appId: '1:188263250841:android:0ca984f81f2a9330557108',
    messagingSenderId: '188263250841',
    projectId: 'app1-1015b',
    storageBucket: 'app1-1015b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMq29klonvrQ4epGrXdXr3MZVj1KpMQI0',
    appId: '1:188263250841:ios:b30d980cfb270e2e557108',
    messagingSenderId: '188263250841',
    projectId: 'app1-1015b',
    storageBucket: 'app1-1015b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMq29klonvrQ4epGrXdXr3MZVj1KpMQI0',
    appId: '1:188263250841:ios:dc6291aaeee3574e557108',
    messagingSenderId: '188263250841',
    projectId: 'app1-1015b',
    storageBucket: 'app1-1015b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
